export const events = {
  MARK_AS_READ: 'MARK AS READ',
  MARK_AS_UNREAD: 'MARK AS UNREAD',
  SHOW_CONTENT: 'SHOW CONTENT',
  FILTER_READ: 'FILTER READ',
  FILTER_UN_READ: 'FILTER UN READ',
  ADD_EMAIL: 'ADD EMAIL',
  DELETE_EMAIL: 'DELETE EMAIL',
  LOAD_EMAIL: 'LOAD EMAIL',
};
